---

rules:
  unpinned-uses:
    config:
      policies:
        "actions/*": ref-pin
        "github/codeql-action/*": ref-pin
        "pypa/gh-action-pypi-publish": ref-pin
        "andreaso/*": ref-pin
        "*": hash-pin
