---

services:
  testrun-py310-constrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3100:3100
    build:
      args:
        pyver: "3.10"
        pip_extra: --constraint=/src/constraints.txt
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-310-constrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py310-unconstrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3100:3100
    build:
      args:
        pyver: "3.10"
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-310-unconstrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py311-constrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3110:3110
    build:
      args:
        pyver: "3.11"
        pip_extra: --constraint=/src/constraints.txt
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-311-constrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py311-unconstrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3110:3110
    build:
      args:
        pyver: "3.11"
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-311-unconstrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py312-constrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3120:3120
    build:
      args:
        pyver: "3.12"
        pip_extra: --constraint=/src/constraints.txt
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-312-constrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py312-unconstrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3120:3120
    build:
      args:
        pyver: "3.12"
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-312-unconstrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py313-constrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3130:3130
    build:
      args:
        pyver: "3.13"
        pip_extra: --constraint=/src/constraints.txt
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-313-constrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  testrun-py313-unconstrained:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    user: 3130:3130
    build:
      args:
        pyver: "3.13"
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      HV4GHA_KEYNAME: test-313-unconstrained
      HV4GHA_VAULT_ADDR: http://vault-server:8200
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
    env_file: .env
    command: [import, issue, issue-scoped]
    depends_on:
      - vault-setup

  vault-setup:
    image: hashicorp/vault
    environment:
      HVGHA_VAULT_IMPORT_TOKEN: CorrectHorseImportKey
      HVGHA_VAULT_SIGN_TOKEN: CorrectHorseSignJWT
      VAULT_TOKEN: BatteryStaple
      VAULT_ADDR: http://vault-server:8200
    volumes:
      - ./setup:/mnt/setup
    entrypoint: /mnt/setup
    depends_on:
      vault-server:
        condition: service_healthy

  vault-server:
    cap_add:
      - IPC_LOCK
    image: hashicorp/vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: BatteryStaple
    healthcheck:
      test: ["CMD", "/usr/bin/nc", "-z", "127.0.0.1", "8200"]
      interval: 1s
      timeout: 1s
      retries: 5
