#!/bin/ash
set -o errexit
set -o nounset
set -o noglob
set -o pipefail

# Required env variables
: "$HVGHA_SETUP_COMMAND"
: "$HVGHA_VAULT_IMPORT_TOKEN"
: "$HVGHA_VAULT_SIGN_TOKEN"

"$HVGHA_SETUP_COMMAND" secrets enable transit

cat <<EOF |
path "transit/wrapping_key" {
  capabilities = ["read"]
}

path "transit/keys/+" {
  capabilities = ["read"]
}

path "transit/keys/+/import" {
  capabilities = ["update"]
}

path "transit/keys/+/import_version" {
  capabilities = ["update"]
}
EOF
"$HVGHA_SETUP_COMMAND" policy write import-key -

cat <<EOF |
path "transit/sign/+" {
  capabilities = ["update"]
}
EOF
"$HVGHA_SETUP_COMMAND" policy write sign-token -

"$HVGHA_SETUP_COMMAND" token create -no-default-policy -policy=import-key -id="$HVGHA_VAULT_IMPORT_TOKEN" -field=token
"$HVGHA_SETUP_COMMAND" token create -no-default-policy -policy=sign-token -id="$HVGHA_VAULT_SIGN_TOKEN" -field=token
